stages:
  - build
  - test

build_job:
  stage: build
  script:
    - dotnet build
    - dotnet publish Sales.Data.Analysis --no-build --output o
  artifacts:
    expire_in: 1 week  
    paths:
      - o
  tags:
    - dotnetcore

test_job:
  stage: test
  script:
    - dotnet add Sales.Data.Analysis.UnitTest package XunitXml.TestLogger --version 2.1.26
    - dotnet add Sales.Data.Analysis.UnitTest package coverlet.msbuild
    - dotnet test --logger "xunit;LogFileName=TestResults.xml" --results-directory ./BuildReports/UnitTests  /p:CollectCoverage=true /p:CoverletOutput=BuildReports\Coverage\  /p:CoverletOutputFormat=cobertura /p:Exclude="[xunit.*]"
  coverage: 'Total.*?([0-9]{1,3})%'
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - 'BuildReports\UnitTests\TestResults.xml'
      - 'BuildReports\Coverage\coverage.cobertura.xml'
    reports:
      junit: 'BuildReports\UnitTests\TestResults.xml'
  needs:
    - build_job
  tags:
    - dotnetcore

