stages:
  - build
  - test

build_job:
  stage: build
  script:
    - dotnet build
    - dotnet publish Sales.Data.Analysis --no-build --output o
  artifacts:
    expire_in: 1 week  
    paths:
      - o
  tags:
    - dotnetcore

test_job:
  stage: test
  script:
    - dotnet add package XunitXml.TestLogger --version 2.1.26
    - dotnet test --logger:"xunit;LogFilePath=TestOutput.xml"
  artifacts:
    when: always  
    expire_in: 1 week 
    paths:
      - 'Sales.Data.Analysis.UnitTest\TestResults\TestOutput.xml'
    reports:
      junit: 'Sales.Data.Analysis.UnitTest\TestResults\TestOutput.xml'
  needs:
    - build_job
  tags:
    - dotnetcore

